## data analysis

In [1]:
import numpy as np 
import pandas as pd 

data = pd.read_csv('/Users/gopesh/nyc dataset experimentation/data/raw/train 2.csv')
data.sample(10)

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
201134,id3998086,2,2016-02-10 00:17:00,2016-02-10 00:36:52,2,-73.986671,40.755093,-73.951447,40.759457,N,1192
337848,id2979602,1,2016-02-06 15:57:03,2016-02-06 16:01:29,1,-73.962242,40.767437,-73.966805,40.770679,N,266
1043366,id2599934,2,2016-06-16 16:27:13,2016-06-16 16:52:13,3,-73.976379,40.764820,-73.954170,40.763840,N,1500
1327530,id1297362,1,2016-01-09 09:39:09,2016-01-09 09:44:14,1,-73.956100,40.781673,-73.963371,40.768898,N,305
628999,id0225590,1,2016-05-05 19:20:42,2016-05-05 19:32:55,1,-73.991295,40.754826,-73.971870,40.761517,N,733
80041,id0224605,2,2016-05-08 18:30:06,2016-05-08 18:42:37,1,-73.975037,40.761150,-73.969131,40.757500,N,751
606039,id0456953,1,2016-02-25 06:11:00,2016-02-25 06:14:37,1,-73.953278,40.771603,-73.963570,40.761803,N,217
916946,id3563572,2,2016-06-08 07:00:05,2016-06-08 07:04:13,1,-73.990898,40.756046,-73.980148,40.761772,N,248
1163453,id1295988,2,2016-03-30 00:24:34,2016-03-30 00:44:44,1,-74.003571,40.722248,-73.886642,40.747147,N,1210
636630,id2710124,1,2016-05-27 09:45:11,2016-05-27 10:00:31,1,-73.977013,40.764408,-73.955086,40.777439,N,920

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458644 entries, 0 to 1458643
Data columns (total 11 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   id                  1458644 non-null  object
 1   vendor_id           1458644 non-null  int64
 2   pickup_datetime     1458644 non-null  object
 3   dropoff_datetime    1458644 non-null  object
 4   passenger_count     1458644 non-null  int64
 5   pickup_longitude    1458644 non-null  float64
 6   pickup_latitude     1458644 non-null  float64
 7   dropoff_longitude   1458644 non-null  float64
 8   dropoff_latitude    1458644 non-null  float64
 9   store_and_fwd_flag  1458644 non-null  object
 10  trip_duration       1458644 non-null  int64
dtypes: float64(4), int64(3), object(4)
memory usage: 122.4+ MB

In [3]:
data.drop(columns=['id' , 'dropoff_datetime'], inplace=True , axis=1)
data.sample(10)

,vendor_id,pickup_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
916578,1,2016-01-02 21:59:34,2,-73.978165,40.750507,-74.008621,40.746613,N,924
50148,1,2016-02-04 12:31:57,1,-73.982056,40.746490,-73.991692,40.754681,N,1768
293008,1,2016-01-21 20:15:16,1,-73.976585,40.739697,-73.867790,40.722515,N,1308
783330,1,2016-06-04 14:47:12,2,-73.788803,40.642090,-73.978897,40.746128,N,2928
366960,2,2016-04-13 10:31:23,1,-73.960815,40.772579,-73.963692,40.768482,N,188
1223858,1,2016-01-09 23:20:13,1,-74.005943,40.739933,-73.976517,40.751457,N,1053
86196,1,2016-05-05 11:08:18,1,-73.987816,40.743488,-74.013359,40.716675,N,1149
553208,2,2016-03-25 12:15:35,1,-73.981018,40.765572,-73.982391,40.773911,N,454
685617,2,2016-05-17 11:50:32,2,-73.962341,40.778969,-73.986076,40.756760,N,2243
1166303,2,2016-03-13 11:16:41,1,-73.981300,40.784199,-73.972443,40.782349,N,257

In [4]:
data['pickup_datetime'] = pd.to_datetime(data['pickup_datetime'])
data['pickup_date'] = data['pickup_datetime'].dt.date
data['pickup_time'] = data['pickup_datetime'].dt.time

data.sample(10)

,vendor_id,pickup_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_date,pickup_time
915976,1,2016-04-07 21:14:34,1,-73.978127,40.751179,-73.963081,40.711830,N,1320,2016-04-07,21:14:34
490611,2,2016-06-12 06:55:29,2,-73.974770,40.753616,-73.975563,40.741478,N,179,2016-06-12,06:55:29
947705,2,2016-01-27 21:53:21,1,-74.000328,40.737732,-73.979950,40.665283,N,1904,2016-01-27,21:53:21
343360,2,2016-03-18 18:25:35,1,-73.995590,40.764400,-73.991364,40.750160,N,740,2016-03-18,18:25:35
871963,1,2016-03-06 22:33:15,1,-74.007385,40.726971,-73.969437,40.795246,N,1102,2016-03-06,22:33:15
1012414,2,2016-03-18 12:25:51,1,-74.011696,40.703060,-74.002708,40.708706,N,246,2016-03-18,12:25:51
573192,2,2016-04-04 16:54:16,2,-73.955017,40.780224,-74.001411,40.733627,N,2173,2016-04-04,16:54:16
191475,1,2016-02-03 16:50:15,1,-73.955620,40.779316,-73.946098,40.773232,N,343,2016-02-03,16:50:15
1434502,1,2016-03-04 00:42:19,2,-73.862808,40.768929,-73.968674,40.801945,N,1337,2016-03-04,00:42:19
129849,1,2016-03-08 16:36:10,1,-73.978615,40.762287,-73.882729,40.769028,N,3635,2016-03-08,16:36:10

In [6]:
data.sample(10)

,vendor_id,pickup_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_date,pickup_time
1337251,1,2016-02-03 13:37:49,2,-73.980705,40.763512,-73.979401,40.755611,N,1521,2016-02-03,13:37:49
91148,1,2016-04-24 17:55:13,1,-73.982101,40.771332,-73.965836,40.754322,N,887,2016-04-24,17:55:13
1114080,2,2016-01-28 18:34:27,1,-73.986320,40.734802,-73.973480,40.748138,N,568,2016-01-28,18:34:27
446545,2,2016-03-18 21:53:30,1,-74.002296,40.729599,-73.995049,40.738434,N,431,2016-03-18,21:53:30
233307,1,2016-03-11 21:16:15,1,-73.985519,40.735523,-73.973251,40.751972,N,467,2016-03-11,21:16:15
1219220,2,2016-02-22 19:25:36,1,-74.002602,40.733795,-73.995605,40.742596,N,287,2016-02-22,19:25:36
67666,1,2016-02-13 16:23:30,1,-73.960732,40.775471,-73.945724,40.775383,N,504,2016-02-13,16:23:30
803899,2,2016-01-30 07:44:08,1,-73.952843,40.780376,-73.901100,40.714233,N,1362,2016-01-30,07:44:08
559387,2,2016-05-11 12:11:25,1,-73.970596,40.761921,-73.999588,40.719330,N,1476,2016-05-11,12:11:25
1301588,2,2016-03-10 16:53:47,1,-73.985229,40.735851,-73.974579,40.761650,N,947,2016-03-10,16:53:47